networks:
  scrapper:
    driver: bridge

volumes:
  prometheus_data:
  postgres_data:
  selenoid_video:

services:
  kaggle-scraper:
    image: ghcr.io/bas-kirill/kaggle-scrapper
    environment:
      - SELENIUM_URL=http://selenium-hub:4444/wd/hub
      - DB_CONNECTION_URL=postgresql://postgres:password@postgres:5432/postgres
    depends_on:
      - selenium-hub
      - postgres

  selenium-hub:
    image: selenium/hub:4.11.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - scrapper

  chrome-1:
    image: selenium/node-chrome:4.11.0
    ports:
      - "5901:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - VNC_NO_PASSWORD=0
      - VNC_PASSWORD=mysecret
    networks:
      - scrapper

  chrome-2:
    image: selenium/node-chrome:4.11.0
    ports:
      - "5902:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - VNC_NO_PASSWORD=0
      - VNC_PASSWORD=mysecret
    networks:
      - scrapper

  postgres:
    image: postgres:17.2
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "4819:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scrapper

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    hostname: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped
    networks:
      - scrapper

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9089:9090"
    restart: unless-stopped
    networks:
      - scrapper